import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { headers } from 'next/headers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const middlewareMessage = headers().get('x-middleware-message');

  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <p>This is from the Layout</p>
          <p>
            Middleware message from headers:{' '}
            <span className="text-red-500">{middlewareMessage}</span>
          </p>
          {children}
        </main>
      </body>
    </html>
  );
}
